### PR TITLE
Update release notes

### PR DESCRIPTION
**Pull request by sujithvm**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by hardik-k-shah** [comment]
Why are we breaking release notes? 
Is it a general practice we are going to follow for all ODFE plugins?

**Comment by sujithvm** [comment]
@hardik-k-shah Yes. All Plugins are going to follow the same.

https://github.com/opendistro-for-elasticsearch/index-management/tree/master/release-notes

https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/tree/master/release-notes

https://github.com/opendistro-for-elasticsearch/sql-odbc/tree/master/release-notes

Other plugins too

**Comment by hardik-k-shah** [comment]
Should we follow this format? 

"release-notes/opendistro-for-elasticsearch-<Plugin_name>.release-notes-<version>.md"

**Comment by vrozov** [comment]
I'd suggest to use the second version: `opendistro-elasticsearch-security.release-notes-<version>.md`

**Comment by hardik-k-shah** [comment]
@alolita  suggestions?

**Comment by alolita** [comment]
@hardik-k-shah release notes naming should be opendistro-for-elasticsearch.security.release-notes-<version>.md

**Comment by sujithvm** [comment]
@alolita The plugin name defined in the plugin descriptor and what elasticsearch would see is `opendistro_security` . https://github.com/opendistro-for-elasticsearch/security/blob/master/plugin-descriptor.properties#L9

**Pull request merged**
