### PR TITLE
Fix security configuration naming on OD-0.9

### PR DESCRIPTION
**Pull request by tclin1023**
Run unit test result:
[INFO] Results:
[INFO]
[WARNING] Tests run: 99, Failures: 0, Errors: 0, Skipped: 4
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ opendistro_security ---
[INFO] Building jar: /home/Opendistro/tc-security-0.9/security/target/opendistro_security-0.9.0.1.jar
[INFO]
[INFO] --- git-commit-id-plugin:2.2.3:validateRevision (validate-the-git-infos) @ opendistro_security ---
[INFO]
[INFO] --- maven-jar-plugin:3.1.0:test-jar (default) @ opendistro_security ---
[INFO] Building jar: /home/Opendistro/tc-security-0.9/security/target/opendistro_security-0.9.0.1-tests.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ opendistro_security ---
[INFO] Installing /home/Opendistro/tc-security-0.9/security/target/opendistro_security-0.9.0.1.jar to /root/.m2/repository/com/amazon/opendistroforelasticsearch/opendistro_security/0.9.0.1/opendistro_security-0.9.0.1.jar
[INFO] Installing /home/Opendistro/tc-security-0.9/security/pom.xml to /root/.m2/repository/com/amazon/opendistroforelasticsearch/opendistro_security/0.9.0.1/opendistro_security-0.9.0.1.pom
[INFO] Installing /home/Opendistro/tc-security-0.9/security/target/opendistro_security-0.9.0.1-tests.jar to /root/.m2/repository/com/amazon/opendistroforelasticsearch/opendistro_security/0.9.0.1/opendistro_security-0.9.0.1-tests.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

### CODE REVIEW

**Comment by hardik-k-shah** [comment]
Can you please create similar PR for 0.10 ?

**Comment by tclin1023** [comment]
> Can you please create similar PR for 0.10 ?

Created

**Comment by hardik-k-shah** [comment]
have you run UT for advanced modules as well after these changes?

**Comment by tclin1023** [comment]
> have you run UT for advanced modules as well after these change

Yes. Please find the result below.
[INFO] Results:
[INFO]
[WARNING] Tests run: 551, Failures: 0, Errors: 0, Skipped: 5
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ opendistro_security_advanced_modules ---
[INFO] Building jar: /Opendistro/tc-security/security-advanced-modules/target/opendistro_security_advanced_modules-0.9.0.1.jar
[INFO]
[INFO] --- git-commit-id-plugin:2.2.3:validateRevision (validate-the-git-infos) @ opendistro_security_advanced_modules ---
[INFO]
[INFO] --- maven-jar-plugin:3.1.0:test-jar (default) @ opendistro_security_advanced_modules ---
[INFO] Building jar: /Opendistro/tc-security/security-advanced-modules/target/opendistro_security_advanced_modules-0.9.0.1-tests.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ opendistro_security_advanced_modules ---
[INFO] Installing /Opendistro/tc-security/security-advanced-modules/target/opendistro_security_advanced_modules-0.9.0.1.jar to /root/.m2/repository/com/amazon/opendistroforelasticsearch/opendistro_security_advanced_modules/0.9.0.1/opendistro_security_advanced_modules-0.9.0.1.jar
[INFO] Installing /Opendistro/tc-security/security-advanced-modules/pom.xml to /root/.m2/repository/com/amazon/opendistroforelasticsearch/opendistro_security_advanced_modules/0.9.0.1/opendistro_security_advanced_modules-0.9.0.1.pom
[INFO] Installing /Opendistro/tc-security/security-advanced-modules/target/opendistro_security_advanced_modules-0.9.0.1-tests.jar to /root/.m2/repository/com/amazon/opendistroforelasticsearch/opendistro_security_advanced_modules/0.9.0.1/opendistro_security_advanced_modules-0.9.0.1-tests.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Pull request merged**
