### PR TITLE
Add actual user roles to context when calling .roles in DLS and FLS.

### PR DESCRIPTION
**Pull request by lucaswin-amzn**
Prior to this change when using `${user.roles}` in DLS or FLS only the user backend roles where used. with this change both the backend roles and actual role mappings are passed to the context variable.

Example log statements before and after this call

```
[2019-08-06T15:23:37,383][INFO ][c.a.o.s.p.DlsFlsEvaluator] [smoketestnode] User before adding all roles: [test-role]
[2019-08-06T15:23:37,383][INFO ][c.a.o.s.p.DlsFlsEvaluator] [smoketestnode] User after adding all roles: [own_index, test-role, alerting_full_access, role for test index]
```

We can clearly see from the `own_index` a role that every user has when using this plugin is present in the roles field. As well as any mappings I had created between this user and the named roles. Roles such as `admin` are left out, as there is no back end role with that name associated to the user, nor is there a role mapping between this user and the role.

Build result:
```
security lucaswin$ mvn clean install
.
.
.
[INFO] Results:
[INFO] 
[WARNING] Tests run: 174, Failures: 0, Errors: 0, Skipped: 6
[INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:3.1.1:jar (default-jar) @ opendistro_security ---
[INFO] Building jar: /Users/lucaswin/Desktop/github/backend-security/security/target/opendistro_security-1.1.0.0.jar
[INFO] 
[INFO] --- git-commit-id-plugin:2.2.6:validateRevision (validate-the-git-infos) @ opendistro_security ---
[INFO] 
[INFO] --- maven-jar-plugin:3.1.1:test-jar (default) @ opendistro_security ---
[INFO] Building jar: /Users/lucaswin/Desktop/github/backend-security/security/target/opendistro_security-1.1.0.0-tests.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ opendistro_security ---
[INFO] Installing /Users/lucaswin/Desktop/github/backend-security/security/target/opendistro_security-1.1.0.0.jar to /Users/lucaswin/.m2/repository/com/amazon/opendistroforelasticsearch/opendistro_security/1.1.0.0/opendistro_security-1.1.0.0.jar
[INFO] Installing /Users/lucaswin/Desktop/github/backend-security/security/pom.xml to /Users/lucaswin/.m2/repository/com/amazon/opendistroforelasticsearch/opendistro_security/1.1.0.0/opendistro_security-1.1.0.0.pom
[INFO] Installing /Users/lucaswin/Desktop/github/backend-security/security/target/opendistro_security-1.1.0.0-tests.jar to /Users/lucaswin/.m2/repository/com/amazon/opendistroforelasticsearch/opendistro_security/1.1.0.0/opendistro_security-1.1.0.0-tests.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11:49 min
[INFO] Finished at: 2019-08-06T15:51:21-07:00
[INFO] ------------------------------------------------------------------------
```

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

### CODE REVIEW

**Comment by hardik-k-shah** [comment]
We should run advanced module UT as well post your changes.

**Comment by lucaswin-amzn** [comment]
> We should run advanced module UT as well post your changes.

I attempted to run these, both locally on a macbook and on a EC2 node with 64gb RAM. Both with and without my changes the tests never complete and simply crash. Could you share some steps on how to get these to complete?

**Comment by lucaswin-amzn** [comment]
Advanced modules tests:
```
[INFO] Tests run: 92, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.307 s - in com.amazon.dlic.auth.ldap2.LdapBackendTestNewStyleConfig2
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 556, Failures: 0, Errors: 0, Skipped: 5
[INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:3.1.1:jar (default-jar) @ opendistro_security_advanced_modules ---
[INFO] Building jar: /security/security-advanced-modules/target/opendistro_security_advanced_modules-1.1.0.1.jar
[INFO] 
[INFO] --- git-commit-id-plugin:2.2.6:validateRevision (validate-the-git-infos) @ opendistro_security_advanced_modules ---
[INFO] 
[INFO] --- maven-jar-plugin:3.1.1:test-jar (default) @ opendistro_security_advanced_modules ---
[INFO] Building jar: /security/security-advanced-modules/target/opendistro_security_advanced_modules-1.1.0.1-tests.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ opendistro_security_advanced_modules ---
[INFO] Installing /security/security-advanced-modules/target/opendistro_security_advanced_modules-1.1.0.1.jar to /root/.m2/repository/com/amazon/opendistroforelasticsearch/opendistro_security_advanced_modules/1.1.0.1/opendistro_security_advanced_modules-1.1.0.1.jar
[INFO] Installing /security/security-advanced-modules/pom.xml to /root/.m2/repository/com/amazon/opendistroforelasticsearch/opendistro_security_advanced_modules/1.1.0.1/opendistro_security_advanced_modules-1.1.0.1.pom
[INFO] Installing /security/security-advanced-modules/target/opendistro_security_advanced_modules-1.1.0.1-tests.jar to /root/.m2/repository/com/amazon/opendistroforelasticsearch/opendistro_security_advanced_modules/1.1.0.1/opendistro_security_advanced_modules-1.1.0.1-tests.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12:00 min
[INFO] Finished at: 2019-08-21T23:48:26Z
[INFO] ------------------------------------------------------------------------
```

**Comment by hardik-k-shah** [comment]
Closing old PR as we need to rework due to conflict and code refactoring post merging three repos.

**Pull request closed without merging**
