### PR TITLE
Alerting roles fix

### PR DESCRIPTION
**Pull request by lucaswin-amzn**
Fix for alerting roles since with security plugin v1.0 the format has changed. The roles still have the same permissions as [this pr](https://github.com/opendistro-for-elasticsearch/security/pull/88).

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

### CODE REVIEW

**Comment by lucaswin-amzn** [comment]
When running while test suite I get a failure:
```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   InitializationIntegrationTests.testDefaultConfig:181 expected:<200> but was:<503>
[INFO] 
[ERROR] Tests run: 174, Failures: 1, Errors: 0, Skipped: 22
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26:02 min
[INFO] Finished at: 2019-07-15T17:15:39-07:00
[INFO] ------------------------------------------------------------------------
```

Running this test manually:

```
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 59.593 s - in com.amazon.opendistroforelasticsearch.security.InitializationIntegrationTests
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

**Comment by hardik-k-shah** [comment]
> When running while test suite I get a failure:
> 
> ```
> [INFO] 
> [INFO] Results:
> [INFO] 
> [ERROR] Failures: 
> [ERROR]   InitializationIntegrationTests.testDefaultConfig:181 expected:<200> but was:<503>
> [INFO] 
> [ERROR] Tests run: 174, Failures: 1, Errors: 0, Skipped: 22
> [INFO] 
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  26:02 min
> [INFO] Finished at: 2019-07-15T17:15:39-07:00
> [INFO] ------------------------------------------------------------------------
> ```
> 
> Running this test manually:
> 
> ```
> [INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 59.593 s - in com.amazon.opendistroforelasticsearch.security.InitializationIntegrationTests
> [INFO] 
> [INFO] Results:
> [INFO] 
> [INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
> [INFO] 
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> ```

Did you re-run entire test suite again?  (our build job can not run failed test indiviually..   can you please make sure all tests passes ?)

**Comment by NihalHarish** [comment]
This seems like a resource issue.
We can try reducing the flakiness of that particular unit test by increasing the wait time before it makes a request.

**Comment by NihalHarish** [comment]
```
[INFO] Results:
[INFO] 
[WARNING] Tests run: 174, Failures: 0, Errors: 0, Skipped: 22
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21:08 min
[INFO] Finished at: 2019-07-16T12:08:29-07:00
[INFO] ------------------------------------------------------------------------
```

All the Unit Tests pass on my laptop.
I think we can merge this PR.

I'll raise another PR to address the flaky unit test.

**Pull request merged**
