### PR TITLE
add AD search task permission to ad read access

### PR DESCRIPTION
**Pull request by ylwu-amzn**
##  opendistro-for-elasticsearch/security pull request intake form
_Please provide as much details as possible to get feedback/acceptance on your PR quickly_

 
 1. __Category:__ (_Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation_)
 Maintenance
 
 
 2. __Github Issue # or road-map entry, if available:__
N/A

 3. __Description of changes:__
Add new AD search task action to AD read access

 4. __Why these changes are required?__ 
Search AD task action should be part of AD read access.

 5. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screen-shot if available_)
We add new API to search AD task.

 6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing and manual testing_)
 No change to actual source. No additional testing needed.
 
 
 7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of them_)
N/A

 8. __Is it backport from master branch?__ (_If yes, please add backport PR # and commits #_)
No

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by hardik-k-shah — APPROVED** [review]

**Review by saratvemulapalli — DISMISSED** [review]

**Comment by cliu123** [comment]
@ylwu-amzn Could you please check why CI/Test is failing?

**Comment by sujithvm** [comment]
Please rebase against master to rerun CI. There was a flaky test unable to bind to a port on Github CI host.

**Comment by ylwu-amzn** [comment]
> Please rebase against master to rerun CI. There was a flaky test unable to bind to a port on Github CI host.

Thanks a lot. Will do this.

**Comment by ylwu-amzn** [comment]
@sujithvm  Now the CI workflow passed. Can you help review and approve?

**Review by saratvemulapalli — APPROVED** [review]

**Review by hardik-k-shah — APPROVED** [review]

**Pull request merged**
