### PR TITLE
Rename security plugin artifacts from opendistro_security to opendistro-security

### PR DESCRIPTION
**Pull request by cliu123**
##  opendistro-for-elasticsearch/security pull request intake form
_Please provide as much details as possible to get feedback/acceptance on your PR quickly_

 
 1. __Category:__ (_Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation_)
 Maintenance
 
 
 2. __Github Issue # or road-map entry, if available:__

 3. __Description of changes:__
Rename .zip file from opendistro_security to opendistro-security to comply with [ODFE artifacts naming convention](https://quip-amazon.com/gmuHA2uDtWHV/ODFE-artifact-naming-convention)

 4. __Why these changes are required?__ 
The [naming convention tracker ](https://quip-amazon.com/7fg8AqP9aMzM/ODFE-artifact-naming-convention-tracker#s:QFO9CAXScUB;QFO9CAPb1Xh) requires security plugin to rename the zip file.

 5. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screen-shot if available_)
Old name: opendistro_security-1.12.0.0.zip
New name: opendistro-security-1.12.0.0.zip

 6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing and manual testing_)
 UT and MT
 
 
 7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of them_)

 8. __Is it backport from master branch?__ (_If yes, please add backport PR # and commits #_)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by vrozov** [comment]
- The scope of the PR is larger than just renaming .zip file. 
- Release notes for existing releases must be preserved.

**Comment by cliu123** [comment]
> * The scope of the PR is larger than just renaming .zip file.
> * Release notes for existing releases must be preserved.

Done.

**Comment by vrozov** [comment]
Both PR and commit message refer to .zip file being renamed. The scope of the PR is more than renaming .zip file.

**Comment by cliu123** [comment]
> Both PR and commit message refer to .zip file being renamed. The scope of the PR is more than renaming .zip file.

Done.

**Review by vrozov — APPROVED** [review]

**Review by gaiksaya — APPROVED** [review]

**Pull request merged**
