### PR TITLE
Update release note 1.13

### PR DESCRIPTION
**Pull request by cliu123**
##  opendistro-for-elasticsearch/security pull request intake form
_Please provide as much details as possible to get feedback/acceptance on your PR quickly_

 
 1. __Category:__ (_Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation_)
 Maintenance
 
 
 2. __Github Issue # or road-map entry, if available:__

 3. __Description of changes:__
Update the release note 1.13 with the newly merged changes.
Note that this PR itself will be included in the update to be included in the release 1.13 release note

 4. __Why these changes are required?__ 
Keep release note updated.

 5. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screen-shot if available_)
No changes in behavior.

 6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing and manual testing_)
 UT
 
 
 7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of them_)

 8. __Is it backport from master branch?__ (_If yes, please add backport PR # and commits #_)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by vrozov** [comment]
I don't see need for this, it is not critical for 1.13 release. If there are any other critical issues required for 1.13, we will include the latest commits from master as well.

**Comment by cliu123** [comment]
> I don't see need for this, it is not critical for 1.13 release. If there are any other critical issues required for 1.13, we will include the latest commits from master as well.

You mean `Fix AuthCredentials equality ([#876](https://github.com/opendistro-for-elasticsearch/security/pull/876))` is not a must-have in release 1.13? If you are not strongly aganst including this one, I'd keep it since it's already been in the master. I'm about to cut the `git tag` for v1.13.0.0-rc1 as soon as this release note updates get merged.

IMO, the other 2 commits should be included since they are related to 1.13.

**Comment by vrozov** [comment]
It is OK to keep the commit on the master, but it is not required for 1.13 release. Please tag 87ff85af3ac3f6b7929ad3a16bca8fd5c10c73ba as 1.13 RC.

**Comment by cliu123** [comment]
> It is OK to keep the commit on the master, but it is not required for 1.13 release. Please tag [87ff85a](https://github.com/opendistro-for-elasticsearch/security/commit/87ff85af3ac3f6b7929ad3a16bca8fd5c10c73ba) as 1.13 RC.

Done.

**Pull request closed without merging**
