### PR TITLE
Replace writeByte with writeShort in TLSUtilTests

### PR DESCRIPTION
**Pull request by cliu123**
##  opendistro-for-elasticsearch/security pull request intake form
_Please provide as much details as possible to get feedback/acceptance on your PR quickly_

 
 1. __Category:__ (_Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation_)
Maintenance 
 
 2. __Github Issue # or road-map entry, if available:__

 3. __Description of changes:__
Replacing writeByte with writeShort in TLSUtilTests to avoid the test failures on CI.

 4. __Why these changes are required?__ 

 5. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screen-shot if available_)
No behavior changes.

 6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing and manual testing_)
 
 
 
 7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of them_)

 8. __Is it backport from master branch?__ (_If yes, please add backport PR # and commits #_)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by vrozov — APPROVED** [review]
It is not a real bug, it is a bug in UT, I would suggest to classify it as maintenance, otherwise looks good.

**Comment by cliu123** [comment]
> It is not a real bug, it is a bug in UT, I would suggest to classify it as maintenance, otherwise looks good.

Done.

**Review by palashhedau — APPROVED** [review]

**Comment by sujithvm** [comment]
Just curious, which CI was build was failing ? Wondering why it was never caught before this

**Comment by cliu123** [comment]
> Just curious, which CI was build was failing ? Wondering why it was never caught before this

Here is the failing CI: https://github.com/opendistro-for-elasticsearch/security/runs/1596706712?check_suite_focus=true
Not sure why the failures never happened in other branches.

**Pull request merged**
