### PR TITLE
Pull request intake form (PR template)

### PR DESCRIPTION
**Pull request by hardik-k-shah**
Creating template for pull request.

*Issue #, if available:* ~None~ 

*Description of changes:*
Creating template for pull request. It will add pull request intake form for Security plugin.  Idea behind creating this template is for asking community members to provide as much details as possible about changes. 

Please suggest any additional/missing questions for this template. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cliu123** [comment]
Is it possible to make the label madatory? Labeling will category the PRs and help release note drafter position the PRs in proper sections in release notes.

**Comment by vrozov** [comment]
It will be good to add category such as enhancement, new functionality, bug fix, refactoring and project maintenance to the template and require certain items only for specific categories. Another option is to use labels, but it is easier to forget to apply label.

**Comment by hardik-k-shah** [comment]
> Is it possible to make the label madatory? Labeling will categorize the PRs and help release note drafter position the PRs in proper sections in release notes automatically.


Added Category field for same.  Not sure if there is a way to make some field mandatory.

**Comment by hardik-k-shah** [comment]
> It will be good to add category such as enhancement, new functionality, bug fix, refactoring and project maintenance to the template and require certain items only for specific categories. Another option is to use labels, but it is easier to forget to apply label.

Added category field.

**Review by vrozov — APPROVED** [review]

**Review by cliu123 — APPROVED** [review]

**Pull request merged**
